config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'flats#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats do
    resources :rentings, only: [:create]
  end

  resources :rentings, except: [:show, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
  belongs_to :user

  has_many :rentings, dependent: :destroy

  validates :address, presence: true
  validates :price, presence: true
end

app/models/renting.rb
class Renting < ApplicationRecord
  belongs_to :user
  belongs_to :flat

  STATUS = ['accepted', 'pending', 'rejected']
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :status, inclusion: { in: STATUS }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :flats, dependent: :destroy
  has_many :rentings, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController

  def index
    @flats = Flat.all
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.user_id = current_user.id
    if @flat.save
      redirect_to flat_path(@flat)
    else
      render :new
    end
  end

  def edit
    @flat = Flat.find(params[:id])
  end

  def update
    @flat = Flat.find(params[:id])
    if @flat.update(flat_params)
      redirect_to flats_path
    else
      render :new
    end
  end

  def destroy
    @flat = Flat.find(params[:id])
    @flat.destroy
    redirect_to flats_path
  end

  private

  def flat_params
    params.require(:flat).permit(:address, :description, :price)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/flats/edit.html.erb
<h1>Modify Flat # <%= @flat.id %></h1>

<%= simple_form_for (@flat) do |f| %>
  <div class="form-input">
    <%= f.input :address, placeholder: "Your flat address" %>
  </div>

  <div class="form-input">
    <%= f.input :description, placeholder: "Description" %>
  </div>

  <div class="form-input">
    <%= f.input :price, placeholder: "Price per night" %>
  </div>

  <div class="btn-form">
    <%= f.submit "Modify your flat", class: "btn-form" %>
  </div>
<% end %>

app/views/flats/index.html.erb
<h1>Flats</h1>

<% @flats.each do |flat| %>
  <div class="card-flat">
    <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/skateboard.jpg" />
    <div class="card-flat-infos">
      <h2>Flat #<%= flat.id%></h2>
      <p><%= flat.address %></p>
      <p><%= flat.description %></p>
      <p><strong><%= flat.price %>€/night</strong></p>
    </div>
    <div>
      <%= link_to edit_flat_path(flat), class: "edit-icon ms-3" do %>
        <i class="fa-solid fa-pen"></i>
      <% end %>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RevisionCertif</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <div class="content-container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>